function getRandomQuote() {
  const quotes = [
  "> [!quote] We are what we repeatedly do. Excellence, then, is not an act, but a habit.\n> Philosopher Aristotle",
  "> [!quote] Strive not to be a success, but rather to be of value.\n> Physicist Scientist Albert Einstein",
  "> [!quote] The only way to do great work is to love what you do.\n> Entrepreneur and Tech Innovator Steve Jobs",
  "> [!quote] Act only according to that maxim whereby you can, at the same time, will that it should become a universal law.\n> Philosopher Immanuel Kant",
  "> [!quote] He who has a why to live can bear almost any how.\n> Philosopher Friedrich Nietzsche",
  "> [!quote] Freedom is what you do with what's been done to you.\n> Philosopher and Writer Jean-Paul Sartre",
  "> [!quote] In the depth of winter, I finally learned that within me there lay an invincible summer.\n> Philosopher and Author Albert Camus",
  "> [!quote] Even the darkest night will end and the sun will rise.\n> Author and Poet Victor Hugo",
  "> [!quote] It is not true that people stop pursuing dreams because they grow old, they grow old because they stop pursuing dreams.\n> Author and Novelist Gabriel García Márquez",
  "> [!quote] It is only with the heart that one can see rightly; what is essential is invisible to the eye.\n> Writer and Aviator Antoine de Saint-Exupéry",
  "> [!quote] Paths are made by walking.\n> Novelist and Writer Franz Kafka",
  "> [!quote] Let everything happen to you: beauty and terror. Just keep going. No feeling is final.\n> Poet and Novelist Rainer Maria Rilke",
  "> [!quote] We are made of star-stuff. We are a way for the universe to know itself.\n> Astronomer and Science Communicator Carl Sagan",
  "> [!quote] The first principle is that you must not fool yourself – and you are the easiest person to fool.\n> Physicist Scientist Richard Feynman",
  "> [!quote] That brain of mine is something more than merely mortal; as time will show.\n> Mathematician and Computer Programmer Ada Lovelace",
  "> [!quote] Look up at the stars and not down at your feet. Try to make sense of what you see, and wonder about what makes the universe exist.\n> Physicist and Cosmologist Stephen Hawking",
  "> [!quote] The future belongs to those who believe in the beauty of their dreams.\n> Diplomat and Political Figure Eleanor Roosevelt",
  "> [!quote] Do your little bit of good where you are; it's those little bits of good put together that overwhelm the world.\n> Bishop and Human Rights Activist Desmond Tutu",
  "> [!quote] One child, one teacher, one book, one pen can change the world.\n> Human Rights Activist Malala Yousafzai",
  "> [!quote] Because you are alive, everything is possible.\n> Buddhist Monk and Peace Activist Thích Nhất Hạnh",
  "> [!quote] When we are no longer able to change a situation, we are challenged to change ourselves.\n> Neurologist and Psychiatrist Viktor Frankl",
  "> [!quote] You do not rise to the level of your goals. You fall to the level of your systems.\n> Author and Productivity Expert James Clear",
  "> [!quote] Play long-term games with long-term people. All returns in life, whether in wealth, relationships, or knowledge, come from compound interest.\n> Entrepreneur and Investor Naval Ravikant",
  "> [!quote] Nothing will work unless you do.\n> Poet and Civil Rights Activist Maya Angelou",
  "> [!quote] Clouds come floating into my life, no longer to carry rain or usher storm, but to add color to my sunset sky.\n> Poet and Writer Rabindranath Tagore",
  "> [!quote] Your living is determined not so much by what life brings to you as by the attitude you bring to life.\n> Writer and Poet Khalil Gibran",
  "> [!quote] Education is the most powerful weapon which you can use to change the world.\n> Statesman and Anti-Apartheid Activist Nelson Mandela",
  "> [!quote] When you want something, all the universe conspires in helping you to achieve it.\n> Lyricist and Novelist Paulo Coelho",
  "> [!quote] An investment in knowledge pays the best interest.\n> Polymath and Statesman Benjamin Franklin",
  "> [!quote] To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.\n> Essayist and Philosopher Ralph Waldo Emerson",
  "> [!quote] Aim for the moon. If you miss, you may hit a star.\n> Businessman and Author W. Clement Stone",
  "> [!quote] Do what you feel in your heart to be right—for you’ll be criticized anyway.\n> Diplomat and Political Figure Eleanor Roosevelt",
  "> [!quote] Alone we can do so little; together we can do so much.\n> Author and Disability Rights Activist Helen Keller",
  "> [!quote] If you are always trying to be normal you will never know how amazing you can be.\n> Poet and Civil Rights Activist Maya Angelou",
  "> [!quote] Success is not final, failure is not fatal: it is the courage to continue that counts.\n> Statesman and Prime Minister Winston Churchill",
  "> [!quote] I have not failed. I've just found 10,000 ways that won't work.\n> Inventor and Businessman Thomas Edison",
  "> [!quote] You will never be happy if you continue to search for what happiness consists of.\n> Philosopher and Author Albert Camus",
  "> [!quote] Luck is what happens when preparation meets opportunity.\n> Philosopher and Statesman Seneca",
  "> [!quote] Very little is needed to make a happy life; it is all within yourself, in your way of thinking.\n> Roman Emperor and Philosopher Marcus Aurelius",
  "> [!quote] Of all the paths you take in life, make sure a few of them are dirt.\n> Naturalist and Environmentalist John Muir",
  "> [!quote] A goal without a plan is just a wish.\n> Writer and Aviator Antoine de Saint-Exupéry",
  "> [!quote] Simplicity is the ultimate sophistication.\n> Polymath and Artist Leonardo da Vinci",
  "> [!quote] In the fight between you and the world, back the world.\n> Novelist and Writer Franz Kafka",
  "> [!quote] Go confidently in the direction of your dreams! Live the life you've imagined.\n> Essayist and Philosopher Henry David Thoreau",
  "> [!quote] The secret of getting ahead is getting started.\n> Writer and Humorist Mark Twain",
  "> [!quote] Your time is limited, so don't waste it living someone else's life.\n> Entrepreneur and Tech Innovator Steve Jobs",
  "> [!quote] If I have seen further it is by standing on the shoulders of Giants.\n> Mathematician and Physicist Isaac Newton",
  "> [!quote] The most courageous act is still to think for yourself. Aloud.\n> Fashion Designer Coco Chanel",
  "> [!quote] All that is gold does not glitter, Not all those who wander are lost.\n> Author and Philologist J.R.R. Tolkien",
  "> [!quote] Life isn't about finding yourself. Life is about creating yourself.\n> Playwright and Critic George Bernard Shaw",
  "> [!quote] It does not matter how slowly you go as long as you do not stop.\n> Philosopher Confucius",
  "> [!quote] Comparison is the thief of joy.\n> Statesman and U.S. President Theodore Roosevelt",
  "> [!quote] Always forgive your enemies; nothing annoys them so much.\n> Playwright and Poet Oscar Wilde",
  "> [!quote] The wound is the place where the Light enters you.\n> Poet and Islamic Scholar Rumi",
  "> [!quote] What we achieve inwardly will change outward reality.\n> Philosopher and Biographer Plutarch",
  "> [!quote] Everything can be taken from a man but one thing: the last of the human freedoms—to choose one’s attitude in any given set of circumstances.\n> Neurologist and Psychiatrist Viktor Frankl",
  "> [!quote] Be like water making its way through cracks. Do not be assertive, but adjust to the object, and you shall find a way around or through it.\n> Martial Artist and Actor Bruce Lee",
  "> [!quote] Not everything that is faced can be changed, but nothing can be changed until it is faced.\n> Writer and Civil Rights Activist James Baldwin",
  "> [!quote] Tell me, what is it you plan to do with your one wild and precious life?\n> Poet Mary Oliver",
  "> [!quote] This is the real secret.\n> Philosopher and Writer Alan Watts",
];
  return quotes[Math.floor(Math.random() * quotes.length)];
}
module.exports = getRandomQuote;
